apiVersion: apps/v1
kind: Deployment
metadata:
  name: hungryman-authentication-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: authentication-service
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
