apiVersion: v1
kind: Service
metadata:
  name: hungryman-api-gateway
  labels:
    app: hungryman-api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 5132
      targetPort: 5132
      protocol: TCP
  selector:
    app: hungryman-api-gateway
